kind: Ingress # Setting the kind
metadata:
  namespace: api-app # Setting the namespace
  name: api-app-ingress # Setting the name of the ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # Setting the ingress class
spec:
  rules:
  - host: ds-api-app.octopus.lab # Setting the domain (taken from /etc/hosts)
    http:
      paths:
      - path: / # Setting the path(homepage)
        pathType: Prefix
        backend:
          service:
            name: api-app-service # Ensuring the service matches the service name
            port:
              number: 80 # Setting the port number traffic will be sent to