apiVersion: v1
kind: Service
metadata:
  name: api-app-service
  namespace: api-app
spec:
  selector:
    app: api-app
  ports:
  - port: 80 # Expose the service on internal port 80
    targetPort: 5000 # Send requests to port 5000 on the pods
