# Creating a PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: {{ .Values.db.namespace }}
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.storage.capacity }} # Storage capacity
  accessModes:
    - {{ .Values.storage.accessMode }} # This specifies that the volume can be mounted as read-write by a single node
  hostPath:
    path: "/data/db" # specifies a directory on the host node's filesystem to use for the storage (inside the container)
  persistentVolumeReclaimPolicy: Retain # This specifies that the volume should not be deleted when the claim is deleted
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeMode: Filesystem # specifies that the volume should be mounted to the Pod as a filesystem
---
# Creating a PersistentVolumeClaim
# The info should match the PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: {{ .Values.db.namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}