apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  namespace: {{ .Values.db.namespace }}
  labels:
    app: {{ .Values.db.label }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.db.service.port }}
    name: {{ .Values.db.label }}
  selector:
    app: {{ .Values.db.label }}